import platform, os
print("\tPlatform Infromation \n")
print('\tVersion: ',platform.python_version())
print('\tVersion Tuple: ',platform.python_version_tuple())
print('\tCompiler: ',platform.python_compiler())
print('\tBuild: ',platform.python_build())
print('\n\tSystem Information\n')
print("\tUname: ",platform.uname())
print("\tSystem: ",platform.system())
print("\tNode: ",platform.node())
print("\tRelease: ",platform.release())
print("\tVersion:",platform.version())
print("\tMachine: ",platform.machine())
print("\tProcessor: ",platform.processor())